# Generated by Django 5.2.6 on 2025-09-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='trailer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cinema',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
