# Generated by Django 5.2.6 on 2025-10-16 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cinema', '0002_cinema_created_at_cinema_trailer_cinema_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актёра', 'verbose_name_plural': 'Актёры'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='cinema',
            options={'verbose_name': 'Кинофильм', 'verbose_name_plural': 'Кинофильмы'},
        ),
        migrations.AlterField(
            model_name='actor',
            name='avatar',
            field=models.ImageField(upload_to='actors', verbose_name='Фото актёра'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='ФИО актёра'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='actors',
            field=models.ManyToManyField(to='online_cinema.actor', verbose_name='Актёры'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='category',
            field=models.ManyToManyField(to='online_cinema.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='country',
            field=models.CharField(max_length=150, verbose_name='Страна(ы)'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='released',
            field=models.CharField(max_length=50, verbose_name='Премьера'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='trailer',
            field=models.TextField(verbose_name='Ссылка трейлёра на Ютуб'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='year',
            field=models.CharField(max_length=20, verbose_name='Год выпуска'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_cinema.cinema', verbose_name='Кинофильм')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
