# Generated by Django 5.2.6 on 2025-10-23 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cinema', '0003_alter_actor_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, verbose_name='Статус Автоиризации')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Фото')),
                ('about', models.CharField(blank=True, max_length=200, null=True, verbose_name='Кратко о себе')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='С какого города')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
