# Generated by Django 5.2.6 on 2025-10-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cinema', '0004_profileuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP посетителя')),
            ],
            options={
                'verbose_name': 'IP посетителя',
                'verbose_name_plural': 'IP посетителей',
            },
        ),
        migrations.RemoveField(
            model_name='cinema',
            name='views',
        ),
        migrations.AddField(
            model_name='cinema',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, to='online_cinema.ipvisitor', verbose_name='Просмотры'),
        ),
    ]
