# Generated by Django 5.2.6 on 2026-01-16 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cinema', '0005_ipvisitor_remove_cinema_views_cinema_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_comments', to='online_cinema.comment', verbose_name='Родитель комментария'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='actors',
            field=models.ManyToManyField(related_name='actors', to='online_cinema.actor', verbose_name='Актёры'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='online_cinema.cinema', verbose_name='Кинофильм'),
        ),
    ]
